version: 2
jobs:
  build:
    branches:
      only:
        - master
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS       
      - run: docker build --rm=false -t sean2525/kanobot .
      - run: docker push sean2525/kanobot
