version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build --rm=false -t sean2525/kanobot .

     # deploy the image
     - run: docker push sean2525/kanobot